### ISSUE TITLE
마이페이지에 나의위치가 눈에 안띄어요

### ISSUE THREAD

**Issue by skagmltn7** [CoffeeDrivenDevelopment/Sangchu-Web#29]
## 📑 개요

![스크린샷 2024-04-07 오후 12 19 19](https://github.com/CoffeeDrivenDevelopment/Sangchu-Web/assets/133394749/603e1f20-e04a-4623-9072-70ed5578b999)

나의 위치를 수정하는 버튼이 눈에 띄였으면 좋겠어요

### 🚀 상세 작업 내용

---

### ⏰ 예상 소요 시간

---

### 📁 ETC

---

**Comment by Park0Juhyun** [comment]
#24 이슈 생성하여 수정하고 있습니다.
