### ISSUE TITLE
온라인/오프라인 가격 추이 숫자 시각화가 안보이는 현상

### ISSUE THREAD

**Issue by skagmltn7** [CoffeeDrivenDevelopment/Sangchu-Web#33]
## 📑 개요

![image](https://github.com/CoffeeDrivenDevelopment/Sangchu-Web/assets/133394749/29b30040-129c-42b5-a019-683edfc64e0a)

### ✅ 버그 체크리스트

- [x] ✍️️ 이슈를 상세히 작성했나요?
- [x] 🏷️ 라벨은 등록했나요?

### 👎 버그 동작 방식

---

 1. 온라인/오프라인 최저가가 숫자로 안보여요
 
### 👍 정상 동작 방식

---

1. 온라인/오프라인 오늘의 최저가를 숫자로 시각화
### 🚀 상세 작업 내용

---

### ⏰ 예상 소요 시간

---

### 📁 ETC

---

**Comment by lalabong** [comment]
완료
